FROM centos:7
MAINTAINER Okada Hayato

WORKDIR /cloud9

RUN yum -y update \
    && yum -y install epel-release \
    && yum -y install nodejs npm \
    && yum -y install git \
    && yum -y install which \
    && yum groupinstall -y development \
    && yum install -y glibc-static \
    && localedef -i ja_JP -f UTF-8 ja_JP.UTF-8 \
    && localedef -i ja_JP -f EUC-JP ja_JP.eucJP \
    && localedef -i ja_JP -f SHIFT_JIS ja_JP.sjis \
    && echo LANG="ja_JP.UTF-8" > /etc/locale.conf \
    && unlink /etc/localtime \
    && ln -s /usr/share/zoneinfo/Japan /etc/localtime \
    && git clone git://github.com/c9/core.git c9sdk \
    && cd c9sdk \
    && scripts/install-sdk.sh

ENV LANG ja_JP.UTF-8

EXPOSE 8181

ENTRYPOINT ["node", "/cloud9/c9sdk/server.js"]
CMD ["--listen", "0.0.0.0", "--auth", ":"]
